### ISSUE TITLE
Support for new dnsmasq syntax

### ISSUE THREAD

**Issue by peterhoeg** [notracking/hosts-blocklists#124]
dnsmasq 2.80 will support a better syntax ref https://github.com/ldir-EDB0/dnsmasq/blob/master/CHANGELOG#L76

Any chance you could generate both formats until 2.80 sees widespread adoption?

**Comment by notracking** [comment]
That's is nice change, thanks for submitting it here! Hopefully they will do something similar for the addn-hosts (will half the size of our current blocklists). I will leave this ticket open for now, not sure on how to approach this atm. 

Do not worry, this will be fixed in time.., when I have the will and a proper 'opinion' about this matter ;)

**Comment by ve6rah** [comment]
Personally I would find this more difficult as I currently use sed to automatically replace 0.0.0.0 with the IPv4 address of my webserver (serving a 1 pixel image for all requests) and replace :: with the IPv6 address of my webserver (serving the same 1 pixel image).

I could probably figure out how to do the same after such a change, but it's certainly not as straightforward.

**Comment by peterhoeg** [comment]
The idea would be to generate both the old and new syntax as there is bound to be *millions* of older equipment out there that will never see an update to dnsmasq v2.80.

**Comment by peterhoeg** [comment]
Fair point.

**Comment by notracking** [comment]
Not going to be implemented for the time being, no practical usecase now.
