### ISSUE TITLE
 Blocklist generator script

### ISSUE THREAD

**Issue by compliment** [notracking/hosts-blocklists#145]
It would be really nice if @notracking published the generator script.

**Comment by notracking** [comment]
I know, but there are still dependencies in my scripts that I do not want to share with the public.
Unfortunately the coming time I will be limiting my maintenance to a bare minimum (only updating whitelist requests), because I'm having very limited amounts of free time (house renovation, newborn, work etc..)

You can star https://github.com/notracking/hosts-blocklists-scripts to receive updates on the scripts.
