### ISSUE TITLE
HostsMan can't read from raw.githubusercontent.com

### ISSUE THREAD

**Issue by timofonic** [notracking/hosts-blocklists#17]
See this, it's the same issue for every content in raw.githubusercontent.com
https://github.com/StevenBlack/hosts/issues/215

**Comment by notracking** [comment]
I'm not familiar with this application, but a quick scan on their website tells me that Hostsman does not support domain based filtering (Windows hosts file also does not support that). 

Our blocklist is designed for use in applications that support both host- and domain-based filtering. Only using the hostname filters will give you insufficient coverage as hostnames that overlap the domain blocks are removed for optimisation.

I highly recommend using a tiny VM with a Dnsmasq instance running on it if you are bound to using Windows only.

I will leave this ticket open for now, because there might be something worth looking in to.
Also please let me know if I'm wrong and this application does support domain filtering.
