### ISSUE TITLE
Whitelist https://app.adjust.com

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#207]
blocked to install authenticator from microsoft

![firefox_OkMFQQXJyE](https://user-images.githubusercontent.com/19517680/71761542-1b21eb00-2efe-11ea-99ae-7efcfec4abe6.png)
![firefox_TxVGFVeJ9F](https://user-images.githubusercontent.com/19517680/71761543-1c531800-2efe-11ea-8693-50e7711bd53a.png)

**Comment by 3xploiton3** [comment]
https://go.microsoft.com/fwlink/?LinkId=869155

**Comment by notracking** [comment]
Strange that MS requires this for a security feature, tells something about their stance against their users...

But anyhow, this is a very commonly used ad tracker and I will not whitelist it because the impact will be to high. I recommend temporarily using a unfiltered dns provider like 1.1.1.1 or whitelisting this locally. 

P.S. the valid redirected url can be extracted, that might also work for you: https://www.microsoft.com/authenticator?cmp=ro5tgz_myvfdy

**Comment by 3xploiton3** [comment]
@notracking thx yeah i cannot setup totp because of this shit
