### ISSUE TITLE
newrelic.com is blocked

### ISSUE THREAD

**Issue by macalimlim** [notracking/hosts-blocklists#229]
I see in domains.txt that newrelic.com is blocked

address=/newrelic.com/0.0.0.0
address=/newrelic.com/::

please remove this on domains.txt
thanks :)

**Comment by bigpresh** [comment]
As a tracking/analytics type outfit, it sounds like something that does belong in a blocklist that blocks trackers, to me.

**Comment by patrickdrd** [comment]
for what is worth: 
https://www.urlvoid.com/scan/newrelic.com/

please advise..

**Comment by notracking** [comment]
As stated, newrelic.com should be blocked.

**Comment by nagisa** [comment]
Is a more granular rule possible here? Newrelic may be used for instrumenting web applications but it can also be a tool for instrumenting and observing properties of non-user-facing applications.

`docs.newrelic.com` and `blog.newrelic.com` are also blocked by this rule, despite those being very unlikely to be used to indirectly track visitors. Similarly the `rpm.newrelic.com` is the newrelic application itself that is also unlikely to track visitors, but may be a critical tool for work.

**Comment by notracking** [comment]
Problem is that their tracking is done from their main domain `newrelic.com`. I can only advise you to add it to your local whitelist, this entry is more than valid for our list, `ads.google.com` will also never be whitelisted because some users require access to it for work.

Code injection via 3rd parties and all the data sharing and collecting / slowing / borking down speeds / increasing attact surfaces should just be exterminated from the web. Our list is designed to get rid of these types of actors as good as is reasonably possible via dns blocking.
