### ISSUE TITLE
Lists Makeover

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#230]
- Ads
https://dsi.ut-capitole.fr/blacklists/download/publicite.tar.gz only 'publicite' list
https://easylist-downloads.adblockplus.org/Liste_AR.txt
https://easylist-downloads.adblockplus.org/advblock.txt
https://easylist-downloads.adblockplus.org/easylist.txt
https://easylist-downloads.adblockplus.org/easylistchina.txt
https://easylist-downloads.adblockplus.org/easylistdutch.txt
https://easylist-downloads.adblockplus.org/easylistgermany.txt
https://easylist-downloads.adblockplus.org/easylistitaly.txt
https://easylist-downloads.adblockplus.org/easylistspanish.txt
https://easylist-downloads.adblockplus.org/liste_fr.txt
https://filters.adtidy.org/extension/chromium/filters/1.txt
https://filters.adtidy.org/extension/chromium/filters/11.txt
https://filters.adtidy.org/extension/chromium/filters/13.txt
https://filters.adtidy.org/extension/chromium/filters/16.txt
https://filters.adtidy.org/extension/chromium/filters/7.txt
https://filters.adtidy.org/extension/chromium/filters/9.txt
https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersDnsmasq.conf
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/StreamingAds/hosts
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt
https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt
https://raw.githubusercontent.com/abpvn/abpvn/master/filter/src/abpvn_general.txt
https://raw.githubusercontent.com/easylist/EasyListHebrew/master/EasyListHebrew.txt
https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
https://raw.githubusercontent.com/jspenguin2017/uBlockProtector/master/uBlockProtectorList.txt
https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt
https://raw.githubusercontent.com/szpeter80/hufilter/master/hufilter.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt
https://raw.githubusercontent.com/yous/YousList/master/youslist.txt
https://www.fanboy.co.nz/enhancedstats.txt
https://www.void.gr/kargig/void-gr-filters.txt

- Cryptomining
https://dehakkelaar.nl/lists/cryptojacking_campaign.list.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list_browser.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt

- Misc
http://pgl.yoyo.org/as/serverlist.php?hostformat=hosts
http://winhelp2002.mvps.org/hosts.txt
https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
https://raw.githubusercontent.com/Kees1958/WS3_annual_most_used_survey_blocklist/master/w3tech_hostfile.txt
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
https://raw.githubusercontent.com/Yhonay/antipopads/master/hosts
https://raw.githubusercontent.com/neoFelhz/neohosts/data/_data/basic/common.txt
https://raw.githubusercontent.com/nextdns/cname-cloaking-blocklist/master/domains
https://raw.githubusercontent.com/vokins/yhosts/master/hosts.txt Excluding legit license servers
https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
https://someonewhocares.org/hosts/hosts/
https://v.firebog.net/hosts/static/w3kbl.txt
https://www.dshield.org/feeds/suspiciousdomains_Medium.txt

- Others
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
https://ssl.bblck.me/blacklists/hosts-file.txt

- Privacy
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt

- Security
http://malwaredomains.lehigh.edu/files/BOOT
http://malwaredomains.lehigh.edu/files/immortal_domains.txt
http://security-research.dyndns.org/pub/malware-feeds/ponmocup-infected-domains-shadowserver.csv
https://data.netlab.360.com/feeds/dga/ccleaner.txt
https://data.netlab.360.com/feeds/dga/dircrypt.txt
https://data.netlab.360.com/feeds/dga/fobber.txt
https://data.netlab.360.com/feeds/dga/matsnu.txt
https://data.netlab.360.com/feeds/dga/tofsee.txt
https://data.netlab.360.com/feeds/dga/xshellghost.txt
https://infosec.cert-pa.it/analyze/listdomains.txt
https://infosharing.cybersaiyan.it/feeds/CS-PIHOLE
https://malc0de.com/bl/BOOT
https://openphish.com/feed.txt only full domain filters
https://osint.bambenekconsulting.com/feeds/c2-dommasterlist-high.txt
https://phishing.army/download/phishing_army_blocklist.txt
https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/gamefake.txt
https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/mobile.txt
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Dead/hosts
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
https://raw.githubusercontent.com/Kees1958/WS3_annual_most_used_survey_blocklist/master/w3tech_hostfile.txt
https://raw.githubusercontent.com/PoorPocketsMcNewHold/SteamScamSites/master/steamscamsite.txt
https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt
https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/.dev-tools/output/domains/ACTIVE/list
https://raw.githubusercontent.com/neoFelhz/neohosts/data/_data/basic/common.txt
https://raw.githubusercontent.com/piwik/referrer-spam-blacklist/master/spammers.txt
https://raw.githubusercontent.com/scafroglia93/hosts-blocklists/master/cert-pa.txt
https://raw.githubusercontent.com/scafroglia93/hosts-blocklists/master/checkpoint.txt
https://raw.githubusercontent.com/scafroglia93/hosts-blocklists/master/citizenlab.txt
https://raw.githubusercontent.com/scafroglia93/hosts-blocklists/master/eset.txt
https://raw.githubusercontent.com/scafroglia93/hosts-blocklists/master/malware-traffic-analysis.txt
https://raw.githubusercontent.com/scafroglia93/hosts-blocklists/master/pan-unit42.txt
https://raw.githubusercontent.com/scafroglia93/hosts-blocklists/master/symantec.txt
https://raw.githubusercontent.com/scafroglia93/hosts-blocklists/master/tgsoft.txt
https://raw.githubusercontent.com/scafroglia93/hosts-blocklists/master/yoroi.txt
https://raw.githubusercontent.com/scafroglia93/hosts-blocklists/master/zscaler.txt
https://raw.githubusercontent.com/stamparm/blackbook/master/blackbook.txt
https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/malicious/bad_service.txt
https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/malicious/ek_fallout.txt
https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/malicious/ek_grandsoft.txt
https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/malicious/ek_neutrino.txt
https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/malicious/ek_purplefox.txt
https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/malicious/ek_radio.txt
https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/malicious/ek_rig.txt
https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/malicious/ek_router.txt
https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/malicious/ek_shade.txt
https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/malicious/ek_spelevo.txt
https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/malicious/ek_underminer.txt
https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/malicious/magentocore.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt
https://www.botvrij.eu/data/ioclist.domain.raw
https://www.botvrij.eu/data/ioclist.hostname.raw
https://www.joewein.net/dl/bl/dom-bl.txt
https://www.joewein.net/dl/bl/dom-bl.txt
https://www.malwaredomainlist.com/hostslist/hosts.txt

**Comment by beerisgood** [comment]
not compatible with PiHole:
https://easylist-downloads.adblockplus.org/Liste_AR.txt
https://easylist-downloads.adblockplus.org/advblock.txt
https://easylist-downloads.adblockplus.org/easylist.txt
https://easylist-downloads.adblockplus.org/easylistchina.txt
https://easylist-downloads.adblockplus.org/easylistdutch.txt
https://easylist-downloads.adblockplus.org/easylistgermany.txt
https://easylist-downloads.adblockplus.org/easylistitaly.txt
https://easylist-downloads.adblockplus.org/easylistspanish.txt
https://easylist-downloads.adblockplus.org/liste_fr.txt
https://filters.adtidy.org/extension/chromium/filters/1.txt
https://filters.adtidy.org/extension/chromium/filters/11.txt
https://filters.adtidy.org/extension/chromium/filters/13.txt
https://filters.adtidy.org/extension/chromium/filters/16.txt
https://filters.adtidy.org/extension/chromium/filters/7.txt
https://filters.adtidy.org/extension/chromium/filters/9.txt
https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt
https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt
https://raw.githubusercontent.com/abpvn/abpvn/master/filter/src/abpvn_general.txt
https://raw.githubusercontent.com/easylist/EasyListHebrew/master/EasyListHebrew.txt
https://raw.githubusercontent.com/jspenguin2017/uBlockProtector/master/uBlockProtectorList.txt
https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt
https://raw.githubusercontent.com/szpeter80/hufilter/master/hufilter.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt
https://raw.githubusercontent.com/yous/YousList/master/youslist.txt
https://www.fanboy.co.nz/enhancedstats.txt
https://www.void.gr/kargig/void-gr-filters.txt
https://openphish.com/feed.txt

Not sure about:
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersDnsmasq.conf
https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list_browser.txt
https://dehakkelaar.nl/lists/cryptojacking_campaign.list.txt
https://data.netlab.360.com/feeds/dga/ccleaner.txt
https://data.netlab.360.com/feeds/dga/dircrypt.txt
https://data.netlab.360.com/feeds/dga/fobber.txt
https://data.netlab.360.com/feeds/dga/matsnu.txt
https://data.netlab.360.com/feeds/dga/tofsee.txt
https://data.netlab.360.com/feeds/dga/xshellghost.txt
https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/.dev-tools/output/domains/ACTIVE/list
https://www.botvrij.eu/data/ioclist.domain.raw
https://www.botvrij.eu/data/ioclist.hostname.raw

Doesn't exist:
https://someonewhocares.org/hosts/hosts/

Useless:
https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt - only include the domain "malware-check.disconnect.me"

Also instead of using the HTTP version 
from "http://pgl.yoyo.org/as/serverlist.php?hostformat=hosts" use the HTTPS version: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext


No TLS version at all. **Highly unsecure!:**
http://winhelp2002.mvps.org/hosts.txt - SSLLabs.com [report](https://www.ssllabs.com/ssltest/analyze.html?d=winhelp2002.mvps.org)
http://malwaredomains.lehigh.edu/files/BOOT + http://malwaredomains.lehigh.edu/files/immortal_domains.txt - SSLLabs [report](https://www.ssllabs.com/ssltest/analyze.html?d=malwaredomains.lehigh.edu)
http://security-research.dyndns.org/pub/malware-feeds/ponmocup-infected-domains-shadowserver.csv - SSLLabs [report](https://www.ssllabs.com/ssltest/analyze.html?d=security-research.dyndns.org)

Site itself looks fishy:
https://malc0de.com/bl/BOOT - Virustotal [repot](https://www.virustotal.com/gui/url/22e9031633d70a919e4928bfc1301cd9fada73cefbfb39d8ca4142ce5bb18063/community)

**Comment by scafroglia93** [comment]
Let's try to find a common point to better organize the list

**Comment by scafroglia93** [comment]
https://someonewhocares.org/hosts/hosts

**Comment by notracking** [comment]
@beerisgood adblockPlus based filters are in fact useful, only the full domain filters are used like `||evilhost.com^`

**Comment by notracking** [comment]
And malc0de is legit, see: http://blog.malc0de.com/

@scafroglia93 I will update this somehow, thinking of keeping a separate file for the lists so that the script directly use it as an input (would also avoid having typo's in the readme)..

**Comment by notracking** [comment]
Reformatting will happen sometime. Nothing else left to do for this issue. closing.
