### ISSUE TITLE
Script request

### ISSUE THREAD

**Issue by tbds** [notracking/hosts-blocklists#3]
Hi,

Can you upload the script that generates the txt files.

Take a look of [FreeContributor](https://github.com/tbds/FreeContributor/).

Thanks

**Comment by cbuijs** [comment]
Freecontributer doesn't aggregate domains. Only unduplicates them. Not
efficient and lists can be way shorter. Also doesn't provide to block
ip-addresses in responses, which can cause leak-through.

Check my "rpz-scum-blocker" project. I will publish the scripts soon
(polishing them still, but are close to 100%). The output files I already
publish.

[ Sent from my mobile, please excuse brevity and/or typos ]
On Jun 30, 2016 12:18, "tbds" <notifications@github.com> wrote:

Hi,

Can you upload the script that generates the txt files.

Take a look of FreeContributor <https://github.com/tbds/FreeContributor/>.

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/notracking/hosts-blocklists/issues/3>, or mute the
thread
<https://github.com/notifications/unsubscribe/AGamUmgzOcwVkmH0DfHPDB7NhtZeswc7ks5qQ-xWgaJpZM4JCVV8>
.

**Comment by notracking** [comment]
These scripts have never been created with the intention of making them public, because initially I only used these block lists on my own server for personal use. It was only some time later when I started sharing the resulting lists with friends, that I decided to simply commit them to Github. This way I had a good platform to keep track of the changes in the generated output and it would also allow others to start using them.

I do not mind sharing my scripts/tool-set with anyone, however in their current state they are not really resource efficient nor user friendly and could even be dangerous for you system if configured or used incorrectly. It will also require a bit more to get the results that are available in this repository then simply running the updater/optimizer.

With the most recent updates to my tool-set I started cleaning up some of the code and making some hard coded settings configurable. I cannot give you a specific ETA but somewhere in the future I will be sharing my work for everyone to enjoy. 

In the meantime everyone is invited to submit any missing and / or incorrect items in the current lists, I am actively curating the results and open for feedback!

**Comment by cbuijs** [comment]
Like we all do :-)

The effort is fully appreciated of course, maybe I have sounded negative.
Not intended.

Same story here. Collecting/aggregating list for a long time and am kind of
a DNS geek. And decided to "go public" on as well... more for the reason
that I actually back up what I did and not loose lot of things over the
years already (many times) :-)

Expect to publish my script as well in a week or two when I find time and
clean it up a bit so it is more "user friendly". We can all share and
contribute.

Cheers,
-Chris.

[ Sent from my mobile, please excuse brevity and/or typos ]

**Comment by cbuijs** [comment]
BTW, my stuff is here: https://github.com/cbuijs

[ Sent from my mobile, please excuse brevity and/or typos ]

**Comment by notracking** [comment]
The scripts will not be released as a part of this project. I am currently working on a addon for squid that will also include this functionality. This new type of filter will not only block on domain level but will also enable the use of adblock-plus based content filters, without requiring the clients on a secured network to use a adblocker at all. This should be the final network wide solution for content and dns / domain filtering of any type of online garbage.
