### ISSUE TITLE
new list -> annual_most_used_survey_blocklist 

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#314]
https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist
@beerisgood (for tips)

**Comment by notracking** [comment]
Thanks for the submission!

This list only holds third-party filters and these filter types will not be included, because it says something about how a filter is being moderated. If `google.com` domain would be a ad serving as a third-party, a filter like this would be perfect. For dns filters this would mean blocking also direct access to `google.com`.
