### ISSUE TITLE
Whitelist www.google.com

### ISSUE THREAD

**Issue by nishaddesilva** [notracking/hosts-blocklists#453]
You are now blocking www.google.com. Please whitelist it.

**Comment by fouyos** [comment]
Was about to open :D
![image](https://user-images.githubusercontent.com/18055365/99490036-96b44b80-299b-11eb-9f73-cca4dd30ca3b.png)

**Comment by QAInsights** [comment]
Came here to raise the issue :)

**Comment by chelseaislan** [comment]
This. I thought Google was down but I found Google Meet works just fine.

**Comment by mikalauskas** [comment]
What the actual hell.

**Comment by notracking** [comment]
Manually fixed and update the script, this one should have been caught.

@mikalauskas The sheer number of hosts does not really allow manual reviewing, that's why we automate thing. First time in 8 years that something like this happens. I've seen manually maintained lists blocking the entire .com extension, humans are more likely to make mistakes. This one will never be blocked again here, for sure..

Sorry for the inconvenience and thanks to all for reporting!
