### ISSUE TITLE
[whitelist] prod-adops-proxy.dnitv.net

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#491]
the domain blocks on-demand streaming of broadcasts on discovery +

Source ->
https://www.discoveryplus.it/

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.

**Comment by DandelionSprout** [comment]
Sorry for noticing this report very, very late, but I only learned about it just now from https://oisd.nl/excludes.php?w=prod-adops-proxy.dnitv.net

I doubt I'd be able to remove that entry from its source list (Dandelion Sprout's Nordic Filters Domains) because the entry is required in the smartphone app version of Discovery+. However, I'll see if I can get creative regarding the desktop browser version.

**Comment by scafroglia93** [comment]
if you open a pull request I remove it immediately

Il sab 10 lug 2021, 08:28 Imre Kristoffer Eilertsen <
***@***.***> ha scritto:

**Comment by scafroglia93** [comment]
Ops sorry

Il sab 10 lug 2021, 08:42 Lorenzo Ori ***@***.***> ha scritto:
