### ISSUE TITLE
cdn1.skrill.com is blocked

### ISSUE THREAD

**Issue by ItsPapaChaos** [notracking/hosts-blocklists#508]
cdn1.skrill.com is being blocked, which prevents users from being able to login to the app.

**Comment by notracking** [comment]
```
./whitelist_test cdn1.skrill.com
HOST: cdn1.skrill.com
HOST: skrill.com
```

This one is not listed.. Might be another list causing this?

**Comment by ItsPapaChaos** [comment]
NextDNS tells me that this list is blocking it. I checked my logs further and it did provide another link, so maybe that is the one?

![EE4B87C0-74A3-4688-85F1-5D872775463C](https://user-images.githubusercontent.com/51421680/109468303-666c5680-7a3a-11eb-91aa-77ebb25f6f43.jpeg)

**Comment by notracking** [comment]
And that one is actually blocked, but also for good reasons. online-metrix.net does device fingerprinting for a business. Why does a payment provider forward all requests from their domains to a sketchy company like that? I would not trust my money with a party like that... (my 2c)

That being said, this one looks like it falls under the same category as whitelisting google ads because a few sites refuse to work otherwise. Whitelisting this will have a negatively influence for all other users who lose protection because one site (that most do not use) will otherwise not work. I need to think about this a bit more. In the meantime I can only recommend whitelisting it locally and send out a complaint to Skrill.

**Comment by notracking** [comment]
I will leave this one in place, unless more stuff will be broken by it.
