### ISSUE TITLE
[feature] auto-remove www. from hostnames

### ISSUE THREAD

**Issue by HellboyPI** [notracking/hosts-blocklists#509]
Hello!
In the version of your list for Adguard Home, the domain doubleclick.net is not fully blocked. 
The entry in the list:
||www.doubleclick.net^

Because of the "www." at the beginning, Adguard Home is not blocking all subdomains of the doubleclick.net domain.
Example:
accounts.doubleclick.net

There are also other domains in your list with "www." at the beginning. "www." should be removed.

It should be investigated if "www[any-number]." at the beginning can also be removed.
Example:
||www4.ad.tomshardware.com^
||www2.ad-server.online^
||www10.indiads.com^

But:
||www3.nationalgeographic.com^
||www3.webhostingtalk.com^
||www91.intel.com^
||www99.zapto.org^
||www3.bloomingdales.com^

These are legit web sites. They should not be in your list. Maybe to remove the source list on which these domains are?

**Comment by notracking** [comment]
Hi thanks! ||doubleclick.net^ has been whitelisted (none wildcard). This has been done to enable the inpage google adlicks, who will still show up if this domain is blocked via dns, but do not function. This domain is not used for 3rd party tracking, but it still is a grey area. Inpage ads like the ones in the google search results are best blocked via a proper content blocker (like uBlock Origin).

I need to doublecheck what to do with that one.

Regarding the hosts with leading 'www.', I've tried to tackle those multiple times (in a automated way), but I never managed to create reliable rules for that. I will have another look at them later (when I have a bit more time).

Will get back on these!

**Comment by notracking** [comment]
Removed some invalids found during this investigation
```
 www.be
 www.inf
```

And from now on www. prefixes will be automatically removed, so those hostname filters will turn into domain based filters, blocking every subdomain. This could lead to some tickets about false positives, but that should be manageable. A lot of these come from honeypot logs (phishing tanks), because of compromised webservers. ~3.5k entries will be updated.

The www[0-9]. entries require manual moderation, will do some of that in time..
