### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by Mausy5043** [notracking/hosts-blocklists#53]
Please consider supporting IPv6.

The way you can do that is to duplicate every line in the `hosts.txt` file and replace on the duplicated line the`0.0.0.0` with `::1`

For example:
```
0.0.0.0 0000mps.webpreview.dsl.net
::1 0000mps.webpreview.dsl.net
0.0.0.0 0001.2waky.com
::1 0001.2waky.com
0.0.0.0 000.gaysexe.free.fr
::1 000.gaysexe.free.fr
0.0.0.0 000owamail0.000webhostapp.com
::1 000owamail0.000webhostapp.com
```
etcetera

**Comment by cbuijs** [comment]
"::1" (localhost) should be "::" to be consistent and use an "all zeroes"
address like IPv4.

-Chris

**Comment by Mausy5043** [comment]
@cbuijs you're right. I confused the 127.0.0.1 equivalent.

**Comment by notracking** [comment]
Do you happen to know how Pi-Hole deals with lists in a ipv6 enabled configuration? 
Will it simple add a ipv4 + ipv6 line to its internal (merged) list?

For implementation I'd prefer to make a separate list in a /ipv6/ directory.

**Comment by notracking** [comment]
Ok, it's doing exactly as you suggested.

https://github.com/pi-hole/pi-hole/blob/5ba413569ea8a4220c7e3bd2fa8c28b33b9e8492/advanced/Scripts/list.sh#L144
https://github.com/pi-hole/pi-hole/blob/1e87850952b6d886674b487f57e47fae1c20dc8a/gravity.sh#L468

**Comment by Mausy5043** [comment]
You could also make a second version of each list one IPv4 and one IPv6. For example `hostsv4.txt and hostsv6.txt` and then people can download and install what they need/want.

**Comment by notracking** [comment]
I would like to prevent having to rename the main "hostnames.txt" and "domains.txt" filenames, because people are using them in auto updates and might not be aware of this change.

I'm moving more towards the direction where we just combine the ipv4&6 hosts in the current files, making the list 2x its current size. This should not influence the performance of Dnsmasq too much and is the best option in regard of backwards compatibility, while keeping the instructions to a bare minimum.

**Comment by notracking** [comment]
Ok, implemented in the update scripts.
Starting with the next autoupdate the blocklists will support both ipv4 & ipv6 (combined into one file)!

**Comment by notracking** [comment]
@Mausy5043 and @cbuijs many, many thanks! This is the reason why I made my list public in the first place. Everything seems to be in place, closing ticket.
