### ISSUE TITLE
domains and hostnames different? 

### ISSUE THREAD

**Issue by Ttech** [notracking/hosts-blocklists#58]
why are there some domains not in both files?

**Comment by notracking** [comment]
Because they are complimatary to eachother. For example:

domains.txt contains filter for `adcompany.com` wich in practice means that all subdomains are blocked, eg `*.adcompany` There is no need to further do any blocking on lets say `ads.adcompany.com` in the hostnames.txt list.

Our lists should be use simultaniosly as described [here](https://github.com/notracking/hosts-blocklists#no-more-ads-tracking-and-other-virtual-garbage)
