### ISSUE TITLE
Threat Intelligence -> blocklistproject.github.io > feedback required

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#622]
Source ->
https://blocklistproject.github.io/Lists/#versions

There are some lists that could be evaluated for a possible merge

**Comment by notracking** [comment]
I've reviewed these in the past and where not added because their base list is a merge of multiple other sources (or at least it seems like it is, because it's not adding much unique entries). Current moderation is mostly for lists that are easy to validate (parental controlled pron lists etc). Not a big deal, just not really useful for us at this point in time. Might re-evaluate them again in the future.
