### ISSUE TITLE
SOHO router is chocking

### ISSUE THREAD

**Issue by sergeevabc** [notracking/hosts-blocklists#63]
Dear @notracking,

I’ve started noticing chocking issues since IPv6 duplicates were added and today router doesn’t start.
Perhaps the former might be mitigated by moving IPv6 to a separate list.
And the latter, I guess, is an error with some host?

```
Apr  1 18:53:04 dnsmasq[3035]: bad option at line 546 of /etc/dnsmasq.adblock
Apr  1 18:53:04 dnsmasq[3035]: FAILED to start up
```

**Comment by notracking** [comment]
Thanks for the feedback!

How do you update the lists?

I'm thinking about adding readme instructions for people on how to download the list using a cron job. Such import script could also easily remove all ipv6 hosts for instance (grep -v "0\.0\.0\.0"). This will avoid having to maintain 2 lists and creating possible confusion on what lists to use for new users.

I find it a bit strange that your dnsmasq seems to be having issues with the current formatting, since the amount of memory is insanely low for the current number of hosts in the lists. Besides that, I'm not getting any loading errors with dnsmasq: ```dnsmasq[2829]: dnsmasq: syntax check OK.```

Can you tell me what's at your line ```546``` in ```/etc/dnsmasq.adblock```?
And I'm interested what version of dnsmasq you are running; is it a very old build?

**Comment by sergeevabc** [comment]
> Can you tell me what's at line 546 in your /etc/dnsmasq.adblock file?

Hmm, today there is no more error messages like the one I initially posted. 

> How do you update the lists?
> What version of dnsmasq do you use?

It’s done automatically by some [cronjob][1] inside [Shibby’s][2] firmware, which relies on dnsmasq 2.76 
```
daemon.info dnsmasq[2322]: started, version 2.76 cachesize 4096
daemon.info dnsmasq[2322]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset Tomato-helper auth no-DNSSEC loop-detect no-inotify
user.info adblock: [1] downloading blacklist - https://raw.github.com/notracking/hosts-blocklists/master/hostnames.txt
user.info adblock: ... [1] found 65317 entries
user.info adblock: activated - 32651 entries
```

Well, it seems to be a false alert then.
Nonetheless, I thank you for a quick reply, @notracking.

[1]: https://pli.io/B3Mdp.png
[2]: http://tomato.groov.pl/?page_id=78
