### ISSUE TITLE
If I run as described with dnsmasq I just get "Unable to connect" boxes all over my web pages

### ISSUE THREAD

**Issue by chrisisbd** [notracking/hosts-blocklists#653]
I have installed the dnsmasq.blacklist.txt as described here and, somewhat as I expected, I now get "Unable to connect" and a bunch of other text where the Ads would have been.

Surely there needs to be a local web server of some sort to provide an empty, very small, page instead of the Ad.

I'm doing this on a dedicated, headless, host which doesn't have any sort of web server running on it.  I can add one of course but it would be helpful if the need for this was indicated in the instructions.

**Comment by chrisisbd** [comment]
This is dnsmasq version 2.80 by the way, so I have the right instructions i I think.

**Comment by notracking** [comment]
This is expected behavior. It can be mitigated with setting up your own webserver that hosts an empty pixel for these requests. Or by installing a browser adblocker like "uBlock Origin". Further dnsmasq support is out of scope for this project. In case it's overblocking you can add whitelist requests to this bugtracker.
