### ISSUE TITLE
gravatar.com blocked

### ISSUE THREAD

**Issue by saveyour** [notracking/hosts-blocklists#7]
any particular reason gravatar.com is blocked ? thanks

**Comment by notracking** [comment]
Gravatar is doing cross domain tracking; even though their TOS could be more clear on what will happen with this data, I gave them the benefit of the doubt because it's the same company as Wordpress. Plus I can imagine that their services are useful to some.. With the next update they will be removed from the blacklist.

**Comment by notracking** [comment]
Thanks for the feedback! Issue is resolved.
