### ISSUE TITLE
add the domain to the blocklist

### ISSUE THREAD

**Issue by Olizja** [notracking/hosts-blocklists#705]
This - huq.io

https://blog.appcensus.io/2021/10/25/what-the-huq/
https://www.vice.com/en/article/5dgmqz/huq-location-data-opt-out-no-consent
https://www.bbc.com/news/technology-59346063

**Comment by CaptainFrosty** [comment]
I agree, should be in the list, though stuff like this should be managed at the app level as well since it's another layer of defense and not subject to needing the right rules. Simply use Bouncer, an indespensible app, to deny location requests to these apps that use this, or if you must have it, have Bouncer remove the permission when you exit. There are also apps on F-Droid that will spoof a fake GPS location. 

Not arguing against the wisdom and necessity of blocklists. Never that. Just making sure ya'll remember to have a multi-layered defense with some redundancy to cover your ass. 😅

**Comment by Olizja** [comment]
> 

I use the notracking filter with other NextDNS filters
Thanks for the advice (many NextDNS users won't see it). I would like the domain to be added to the blocklist.

**Comment by Olizja** [comment]
UPD:
https://github.com/AdAway/adaway.github.io/issues/297#issuecomment-993722867

**Comment by CaptainFrosty** [comment]
Sorry, wasn't trying to lecture, and I dunno why I assumed you were on Android. I just wonder how well a blocklist would work for that in the long run…what with many of these companies using CDNs with the domain changing on a whim. Wildcards would help quite a bit, though sadly my Adguard client doesn't seem to support wildcards. Rejected all the rules. I need to rent a VPS or something anyway and get all my blocking off the LAN and my PC's resources. It says in the readme that this list is ‵optimized´ for wildcards, but there aren't any I can see, so I'm a little confused.

**Comment by notracking** [comment]
Thanks, I've added them to the custom blocklist, including the ones additionally found by Jawz.
