### ISSUE TITLE
[Question] About the different lists

### ISSUE THREAD

**Issue by Bundy01** [notracking/hosts-blocklists#721]
I noticed that the 'hostnames' list and the 'unbound' list do not have the same number of domains.
What is the reason for this?

Regards.

**Comment by notracking** [comment]
The coverage is about the same and they are moderated equally. The hostnames blocklist should always be used in combination with the domains filter (both in the root of this repository) to get the full coverage as any of the other versions.

Hostname filters are designed not to target any of its subdomains `an.evil.host.com`. You can view them as a more refined targeted block, while domain filters block the domain and all its subhosts `*.an.evil.host.com`

Originally the notracking list was only intended for use with dnsmasq, but this changed over time. Also all mayor dns solutions do not offer such specific targeting and mostely just block as a wildcard `*.an.evil.host.com`, which in practice works just fine. So for now one could consider the 2 files `hostnames.txt` and `domains.txt` in the root of the repos as obsolete (they will be kept alive and updated exactly the same as any of the other lists, because I do not like breaking old configurations of people still using those versions).

**Comment by Bundy01** [comment]
Thank you for this clarification :). I close
