### ISSUE TITLE
SimpleLogin pages broken

### ISSUE THREAD

**Issue by mpeter50** [notracking/hosts-blocklists#749]
It looks like simplelogin.co has got on one of the blocklists that you use:

![image](https://user-images.githubusercontent.com/83356418/159933571-7727f323-94e2-4f29-895b-c60bfedcdf14.png)

This results in the SimpleLogin login page and other parts of their web app not working.

Could you take a look at this, please?

**Comment by lanuk** [comment]
It's coming from https://www.stopforumspam.com/downloads/toxic_domains_whole.txt

**Comment by mpeter50** [comment]
Well, this is an interesting service. They cannot be contacted from a private email, at all, because either their own spam detection trips, or that "my email address is not listed" (yeha, because it isn't, only the domain is..).

I don't want to register to their forum with my real email address, so they can do whatever they want.

However, first of all, thank you for letting me know where does the listing come from.
Secondly, would you please consider whitelisting this domain name?

**Comment by jfdl1991** [comment]
You're very wrong about them! That service is suprerb! And free. Even premium is free for students!
That are the ultimate tool for email privacy!
I wrote a complete description of what they do and how can protect you from any email type of attack and tracking but my damn phone died.
They are not like disposable mails like guerrillamail. They are kind of a proxy between you and the other email. They just resend mails written to an alias email you (and only you) possess and asociate it to you real private inbox and vice versa. 
They are our allies to avoid tracking wich is the purpose of this Git isn't it?
And you can contac them!
hi@simplelogin.io

If they are triggering anything "evil" is just because probably the service have been used badly by someone!

See: https://simplelogin.io/docs/
https://github.com/simple-login

**Comment by mpeter50** [comment]
> You're very wrong about them! That service is suprerb! And free. Even premium is free for students! That are the ultimate tool for email privacy! I wrote a complete description of what they do and how can protect you from any email type of attack and tracking but my damn phone died. They are not like disposable mails like guerrillamail. They are kind of a proxy between you and the other email. They just resend mails written to an alias email you (and only you) possess and asociate it to you real private inbox and vice versa. They are our allies to avoid tracking wich is the purpose of this Git isn't it? And you can contac them! [hi@simplelogin.io](mailto:hi@simplelogin.io)
> 
> If they are triggering anything "evil" is just because probably the service have been used badly by someone!
> 
> See: https://simplelogin.io/docs/ https://github.com/simple-login

If you responded to me, I know that, thanks. I'm too a happy user of SimpleLogin. I was speaking about stopforumspam.
I wanted to write a message to stopforumspam that is similar to yours (I've even took the time to write it in notepad..), but I wasn't able to send the message to them, because their complaint pages are.. not too good.

On the other hand, I didn't know pro is free for students! Thanks for letting me know.
