### ISSUE TITLE
Why "Not Trusted"

### ISSUE THREAD

**Issue by RicoHeat** [notracking/hosts-blocklists#791]
@notracking I'm curious as to why you don't trust @badmojr the creator of https://github.com/badmojr/1Hosts/

1) Lists are very well maintained ✔
2) High efficiency with less size compared to other well known lists ✔
3) @badmojr is easily accessible for issues or suggestions ✔

Maybe you should get to know @badmojr better before passing any judgment. 

Not trying to start any issues.. Just trying to start an open and honest conversation.

Have a great day! 😁👌

**Comment by notracking** [comment]
I've added this exclusion a very long time ago, likely because back then some tricky false positives showed up. The comment is for sure nothing personal towards @badmojr but it referrers to the state of the blocklist.

Just checked again and 1host is a merged list from various sources, for that reason it will not be included (I prefer adding the source lists instead).

All the best for your work @badmojr I hope I did not hurt your feelings with my notes ;)
