### ISSUE TITLE
Why two files

### ISSUE THREAD

**Issue by mscreenie** [notracking/hosts-blocklists#8]
excuse my question but why are there two files needed ? Can't this be achived by just domains.txt? Also is there a way to allow for ads but to block tracking?

Reason, many sites now require ads but it is still desirable to block tracking.

**Comment by notracking** [comment]
The domain filter will block any hostname that matches like a wildcard, eg *.blockeddomain.com
For the hostname filter it will only block if it has a exact match with the filter.

For example (domain filter):
'address=/ads.google.com/0.0.0.0'
will block '1.ads.google.com', 'ads.google.com', '1.2.3.ads.google.com' etc.

Hostname filter:
'0.0.0.0 ads.google.com'
will block 'ads.google.com'
will not block '1.ads.google.com', '1.2.3.ads.google.com' etc.

Separating ad from tracking filters is not feasible, since ads will also track you.. there is not clear distinction in most cases. If one of the filters is breaking useful functionality you can always submit a ticket and I will review and whitelist if found to be a real false call. 

Whitelisting generic trackers such as google adsense, because some sites will force their user to use it will not be considered as a false call. These kind of sites try to force their users to be exposed to privacy invasion and malware infections and should therefore simply not be used anymore.

However, these type of adblock-blockers can be easily bypassed by using 'uBlock Origin'. This content blocker is capable of injecting specially crafted javascript or css to fool these kind of counter measures, while still blocking all their trackers & ads. 'uBlock Origin' works perfectly in combination with our blocking lists.

**Comment by mscreenie** [comment]
I see thanks for the explanation. Appreciated. I agree, adverts serve dual functionality now. I had this setup on my openwrt install and was working beautifully until we decided to do some shopping, lots of comparison sites use tracking and referral adding services, needless to say those sites were non functional. 

I am considering making a list of trackers still, it won't be total privacy. A list for dedicated trackers and analytics platforms like Google urchin etc.
