### ISSUE TITLE
publish the whitelist

### ISSUE THREAD

**Issue by Mausy5043** [notracking/hosts-blocklists#85]
It would be great if you could also publish your whitelist.  
That way we know what will not get blocked.

**Comment by notracking** [comment]
I've been thinking about that as well, though making the whitelist public could also help the baddies with countering the dns filters.. Not sure how I will share it, since I really want to keep this repos as simple as possible: having an extra whitelist file could confuse people and I don't want to have to put extra effort in my workflow of keeping things up to date.

I will have another look at this as soon as I'm back from my vacation.

**Comment by notracking** [comment]
And [here](https://github.com/notracking/hosts-blocklists-scripts/blob/master/hostnames.whitelist.txt) you go!
